export const CREATE_CAMPAIGN_PAYLOAD = {
  step: null,
  sender: '',
  name: 'INSTRUCTION MEGJ',
  campaignType: 'SIMPLE',
  recipientSource: 'CUSTOM',
  groupId: null,
  filename: null,
  saveAsModel: false,
  destination: 'NAT_INTER',
  message: 'message',
  emailText: null,
  recipients: [],
  sendAt: [],
  dlrUrl: '',
  responseUrl: '',
};
